/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bet {
  'id' : bigint,
  'userId' : Principal,
  'selectedOutcome' : MatchResult,
  'betStatus' : BetStatus,
  'stake' : bigint,
  'matchId' : bigint,
  'timestamp' : Time,
}
export type BetStatus = { 'won' : null } |
  { 'pending' : null } |
  { 'lost' : null };
export interface Match {
  'id' : bigint,
  'status' : MatchStatus,
  'result' : MatchResult,
  'homeTeam' : string,
  'createdBy' : Principal,
  'sport' : Sport,
  'awayTeam' : string,
  'matchDate' : Time,
}
export type MatchResult = { 'pending' : null } |
  { 'draw' : null } |
  { 'homeWin' : null } |
  { 'awayWin' : null };
export type MatchStatus = { 'upcoming' : null } |
  { 'settled' : null } |
  { 'live' : null };
export interface PlatformStats {
  'totalMatches' : bigint,
  'totalBets' : bigint,
  'totalWithdrawn' : bigint,
  'totalUsers' : bigint,
}
export type Sport = { 'basketball' : null } |
  { 'football' : null } |
  { 'rugby' : null };
export type Time = bigint;
export interface UserProfile {
  'id' : Principal,
  'balance' : bigint,
  'displayName' : string,
  'registrationDate' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WithdrawalRequest {
  'id' : bigint,
  'status' : WithdrawalStatus,
  'userId' : Principal,
  'timestamp' : Time,
  'phoneNumber' : string,
  'amount' : bigint,
}
export type WithdrawalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveWithdrawal' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMatch' : ActorMethod<[string, string, Sport, Time], bigint>,
  'deposit' : ActorMethod<[bigint], undefined>,
  'getAllBets' : ActorMethod<[], Array<Bet>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getAllWithdrawals' : ActorMethod<[], Array<WithdrawalRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMatches' : ActorMethod<[], Array<Match>>,
  'getPlatformStats' : ActorMethod<[], PlatformStats>,
  'getUserBets' : ActorMethod<[], Array<Bet>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserWithdrawals' : ActorMethod<[], Array<WithdrawalRequest>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeBet' : ActorMethod<[bigint, MatchResult, bigint], bigint>,
  'rejectWithdrawal' : ActorMethod<[bigint], undefined>,
  'requestWithdrawal' : ActorMethod<[bigint, string], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'settleMatch' : ActorMethod<[bigint, MatchResult], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];