/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Sport = IDL.Variant({
  'basketball' : IDL.Null,
  'football' : IDL.Null,
  'rugby' : IDL.Null,
});
export const Time = IDL.Int;
export const MatchResult = IDL.Variant({
  'pending' : IDL.Null,
  'draw' : IDL.Null,
  'homeWin' : IDL.Null,
  'awayWin' : IDL.Null,
});
export const BetStatus = IDL.Variant({
  'won' : IDL.Null,
  'pending' : IDL.Null,
  'lost' : IDL.Null,
});
export const Bet = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'selectedOutcome' : MatchResult,
  'betStatus' : BetStatus,
  'stake' : IDL.Nat,
  'matchId' : IDL.Nat,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'balance' : IDL.Nat,
  'displayName' : IDL.Text,
  'registrationDate' : Time,
});
export const WithdrawalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const WithdrawalRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : WithdrawalStatus,
  'userId' : IDL.Principal,
  'timestamp' : Time,
  'phoneNumber' : IDL.Text,
  'amount' : IDL.Nat,
});
export const MatchStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'settled' : IDL.Null,
  'live' : IDL.Null,
});
export const Match = IDL.Record({
  'id' : IDL.Nat,
  'status' : MatchStatus,
  'result' : MatchResult,
  'homeTeam' : IDL.Text,
  'createdBy' : IDL.Principal,
  'sport' : Sport,
  'awayTeam' : IDL.Text,
  'matchDate' : Time,
});
export const PlatformStats = IDL.Record({
  'totalMatches' : IDL.Nat,
  'totalBets' : IDL.Nat,
  'totalWithdrawn' : IDL.Nat,
  'totalUsers' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveWithdrawal' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMatch' : IDL.Func([IDL.Text, IDL.Text, Sport, Time], [IDL.Nat], []),
  'deposit' : IDL.Func([IDL.Nat], [], []),
  'getAllBets' : IDL.Func([], [IDL.Vec(Bet)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllWithdrawals' : IDL.Func([], [IDL.Vec(WithdrawalRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
  'getUserBets' : IDL.Func([], [IDL.Vec(Bet)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserWithdrawals' : IDL.Func([], [IDL.Vec(WithdrawalRequest)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeBet' : IDL.Func([IDL.Nat, MatchResult, IDL.Nat], [IDL.Nat], []),
  'rejectWithdrawal' : IDL.Func([IDL.Nat], [], []),
  'requestWithdrawal' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'settleMatch' : IDL.Func([IDL.Nat, MatchResult], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Sport = IDL.Variant({
    'basketball' : IDL.Null,
    'football' : IDL.Null,
    'rugby' : IDL.Null,
  });
  const Time = IDL.Int;
  const MatchResult = IDL.Variant({
    'pending' : IDL.Null,
    'draw' : IDL.Null,
    'homeWin' : IDL.Null,
    'awayWin' : IDL.Null,
  });
  const BetStatus = IDL.Variant({
    'won' : IDL.Null,
    'pending' : IDL.Null,
    'lost' : IDL.Null,
  });
  const Bet = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'selectedOutcome' : MatchResult,
    'betStatus' : BetStatus,
    'stake' : IDL.Nat,
    'matchId' : IDL.Nat,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'balance' : IDL.Nat,
    'displayName' : IDL.Text,
    'registrationDate' : Time,
  });
  const WithdrawalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const WithdrawalRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : WithdrawalStatus,
    'userId' : IDL.Principal,
    'timestamp' : Time,
    'phoneNumber' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const MatchStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'settled' : IDL.Null,
    'live' : IDL.Null,
  });
  const Match = IDL.Record({
    'id' : IDL.Nat,
    'status' : MatchStatus,
    'result' : MatchResult,
    'homeTeam' : IDL.Text,
    'createdBy' : IDL.Principal,
    'sport' : Sport,
    'awayTeam' : IDL.Text,
    'matchDate' : Time,
  });
  const PlatformStats = IDL.Record({
    'totalMatches' : IDL.Nat,
    'totalBets' : IDL.Nat,
    'totalWithdrawn' : IDL.Nat,
    'totalUsers' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveWithdrawal' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMatch' : IDL.Func([IDL.Text, IDL.Text, Sport, Time], [IDL.Nat], []),
    'deposit' : IDL.Func([IDL.Nat], [], []),
    'getAllBets' : IDL.Func([], [IDL.Vec(Bet)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllWithdrawals' : IDL.Func([], [IDL.Vec(WithdrawalRequest)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
    'getUserBets' : IDL.Func([], [IDL.Vec(Bet)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserWithdrawals' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeBet' : IDL.Func([IDL.Nat, MatchResult, IDL.Nat], [IDL.Nat], []),
    'rejectWithdrawal' : IDL.Func([IDL.Nat], [], []),
    'requestWithdrawal' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'settleMatch' : IDL.Func([IDL.Nat, MatchResult], [], []),
  });
};

export const init = ({ IDL }) => { return []; };