/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Bet {
    id: bigint;
    userId: Principal;
    selectedOutcome: MatchResult;
    betStatus: BetStatus;
    stake: bigint;
    matchId: bigint;
    timestamp: Time;
}
export interface WithdrawalRequest {
    id: bigint;
    status: WithdrawalStatus;
    userId: Principal;
    timestamp: Time;
    phoneNumber: string;
    amount: bigint;
}
export interface PlatformStats {
    totalMatches: bigint;
    totalBets: bigint;
    totalWithdrawn: bigint;
    totalUsers: bigint;
}
export interface UserProfile {
    id: Principal;
    balance: bigint;
    displayName: string;
    registrationDate: Time;
}
export interface Match {
    id: bigint;
    status: MatchStatus;
    result: MatchResult;
    homeTeam: string;
    createdBy: Principal;
    sport: Sport;
    awayTeam: string;
    matchDate: Time;
}
export enum BetStatus {
    won = "won",
    pending = "pending",
    lost = "lost"
}
export enum MatchResult {
    pending = "pending",
    draw = "draw",
    homeWin = "homeWin",
    awayWin = "awayWin"
}
export enum MatchStatus {
    upcoming = "upcoming",
    settled = "settled",
    live = "live"
}
export enum Sport {
    basketball = "basketball",
    football = "football",
    rugby = "rugby"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum WithdrawalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    approveWithdrawal(withdrawalId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createMatch(homeTeam: string, awayTeam: string, sport: Sport, matchDate: Time): Promise<bigint>;
    deposit(amount: bigint): Promise<void>;
    getAllBets(): Promise<Array<Bet>>;
    getAllUsers(): Promise<Array<UserProfile>>;
    getAllWithdrawals(): Promise<Array<WithdrawalRequest>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMatches(): Promise<Array<Match>>;
    getPlatformStats(): Promise<PlatformStats>;
    getUserBets(): Promise<Array<Bet>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserWithdrawals(): Promise<Array<WithdrawalRequest>>;
    isCallerAdmin(): Promise<boolean>;
    placeBet(matchId: bigint, outcome: MatchResult, stake: bigint): Promise<bigint>;
    rejectWithdrawal(withdrawalId: bigint): Promise<void>;
    requestWithdrawal(amount: bigint, phoneNumber: string): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    settleMatch(matchId: bigint, result: MatchResult): Promise<void>;
}
import type { Bet as _Bet, BetStatus as _BetStatus, Match as _Match, MatchResult as _MatchResult, MatchStatus as _MatchStatus, Sport as _Sport, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, WithdrawalRequest as _WithdrawalRequest, WithdrawalStatus as _WithdrawalStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approveWithdrawal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveWithdrawal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveWithdrawal(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createMatch(arg0: string, arg1: string, arg2: Sport, arg3: Time): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createMatch(arg0, arg1, to_candid_Sport_n3(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMatch(arg0, arg1, to_candid_Sport_n3(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async deposit(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deposit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deposit(arg0);
            return result;
        }
    }
    async getAllBets(): Promise<Array<Bet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBets();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBets();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getAllWithdrawals(): Promise<Array<WithdrawalRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWithdrawals();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWithdrawals();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatches(): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatches();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatches();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlatformStats(): Promise<PlatformStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformStats();
            return result;
        }
    }
    async getUserBets(): Promise<Array<Bet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBets();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBets();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserWithdrawals(): Promise<Array<WithdrawalRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserWithdrawals();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserWithdrawals();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async placeBet(arg0: bigint, arg1: MatchResult, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.placeBet(arg0, to_candid_MatchResult_n27(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeBet(arg0, to_candid_MatchResult_n27(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async rejectWithdrawal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectWithdrawal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectWithdrawal(arg0);
            return result;
        }
    }
    async requestWithdrawal(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.requestWithdrawal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestWithdrawal(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async settleMatch(arg0: bigint, arg1: MatchResult): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.settleMatch(arg0, to_candid_MatchResult_n27(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.settleMatch(arg0, to_candid_MatchResult_n27(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_BetStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BetStatus): BetStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Bet_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bet): Bet {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_MatchResult_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchResult): MatchResult {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_MatchStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchStatus): MatchStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Match_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Match): Match {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Sport_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sport): Sport {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalRequest_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalRequest): WithdrawalRequest {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalStatus): WithdrawalStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _WithdrawalStatus;
    userId: Principal;
    timestamp: _Time;
    phoneNumber: string;
    amount: bigint;
}): {
    id: bigint;
    status: WithdrawalStatus;
    userId: Principal;
    timestamp: Time;
    phoneNumber: string;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_WithdrawalStatus_n15(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        timestamp: value.timestamp,
        phoneNumber: value.phoneNumber,
        amount: value.amount
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _MatchStatus;
    result: _MatchResult;
    homeTeam: string;
    createdBy: Principal;
    sport: _Sport;
    awayTeam: string;
    matchDate: _Time;
}): {
    id: bigint;
    status: MatchStatus;
    result: MatchResult;
    homeTeam: string;
    createdBy: Principal;
    sport: Sport;
    awayTeam: string;
    matchDate: Time;
} {
    return {
        id: value.id,
        status: from_candid_MatchStatus_n23(_uploadFile, _downloadFile, value.status),
        result: from_candid_MatchResult_n8(_uploadFile, _downloadFile, value.result),
        homeTeam: value.homeTeam,
        createdBy: value.createdBy,
        sport: from_candid_Sport_n25(_uploadFile, _downloadFile, value.sport),
        awayTeam: value.awayTeam,
        matchDate: value.matchDate
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    userId: Principal;
    selectedOutcome: _MatchResult;
    betStatus: _BetStatus;
    stake: bigint;
    matchId: bigint;
    timestamp: _Time;
}): {
    id: bigint;
    userId: Principal;
    selectedOutcome: MatchResult;
    betStatus: BetStatus;
    stake: bigint;
    matchId: bigint;
    timestamp: Time;
} {
    return {
        id: value.id,
        userId: value.userId,
        selectedOutcome: from_candid_MatchResult_n8(_uploadFile, _downloadFile, value.selectedOutcome),
        betStatus: from_candid_BetStatus_n10(_uploadFile, _downloadFile, value.betStatus),
        stake: value.stake,
        matchId: value.matchId,
        timestamp: value.timestamp
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    won: null;
} | {
    pending: null;
} | {
    lost: null;
}): BetStatus {
    return "won" in value ? BetStatus.won : "pending" in value ? BetStatus.pending : "lost" in value ? BetStatus.lost : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): WithdrawalStatus {
    return "pending" in value ? WithdrawalStatus.pending : "approved" in value ? WithdrawalStatus.approved : "rejected" in value ? WithdrawalStatus.rejected : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upcoming: null;
} | {
    settled: null;
} | {
    live: null;
}): MatchStatus {
    return "upcoming" in value ? MatchStatus.upcoming : "settled" in value ? MatchStatus.settled : "live" in value ? MatchStatus.live : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    basketball: null;
} | {
    football: null;
} | {
    rugby: null;
}): Sport {
    return "basketball" in value ? Sport.basketball : "football" in value ? Sport.football : "rugby" in value ? Sport.rugby : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    draw: null;
} | {
    homeWin: null;
} | {
    awayWin: null;
}): MatchResult {
    return "pending" in value ? MatchResult.pending : "draw" in value ? MatchResult.draw : "homeWin" in value ? MatchResult.homeWin : "awayWin" in value ? MatchResult.awayWin : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WithdrawalRequest>): Array<WithdrawalRequest> {
    return value.map((x)=>from_candid_WithdrawalRequest_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Match>): Array<Match> {
    return value.map((x)=>from_candid_Match_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Bet>): Array<Bet> {
    return value.map((x)=>from_candid_Bet_n6(_uploadFile, _downloadFile, x));
}
function to_candid_MatchResult_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchResult): _MatchResult {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_Sport_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sport): _Sport {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchResult): {
    pending: null;
} | {
    draw: null;
} | {
    homeWin: null;
} | {
    awayWin: null;
} {
    return value == MatchResult.pending ? {
        pending: null
    } : value == MatchResult.draw ? {
        draw: null
    } : value == MatchResult.homeWin ? {
        homeWin: null
    } : value == MatchResult.awayWin ? {
        awayWin: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sport): {
    basketball: null;
} | {
    football: null;
} | {
    rugby: null;
} {
    return value == Sport.basketball ? {
        basketball: null
    } : value == Sport.football ? {
        football: null
    } : value == Sport.rugby ? {
        rugby: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
